### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by aloredo312** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-aloredo312#1]
<img width="833" alt="deliverable_1" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-aloredo312/assets/143145658/9be5ff14-b54c-4bbc-ae6a-7570047c9435">

**Comment by instructorc** [comment]
Deliverable 1 met!
