### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by aloredo312** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-aloredo312#2]
<img width="833" alt="deliverable_2" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-aloredo312/assets/143145658/8ca861e0-1ab3-44d6-8769-b2ea0a5a40a8">

**Comment by instructorc** [comment]
Deliverable #2 met!
